---
# Homepage configuration
# See https://fontawesome.com/search for icons options

title: "Nav"
subtitle: "Learnder"
logo: "/assets/icons/logo.png"
header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span>, Run by <a href="https://learnder.og">Learnder</a>.</p>'

columns: 3
connectivityCheck: true

defaults:
  layout: list
  colorTheme: auto

theme: default

stylesheet:
   - "assets/custom.css"

colors:
  light:
    highlight-primary: "#7097B6"
    highlight-secondary: "#a0b9ce"
    highlight-hover: "#b8cada"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#7097B6"
    link-hover: "#a0b9ce"
  dark:
    highlight-primary: "#7097B6"
    highlight-secondary: "#a0b9ce"
    highlight-hover: "#b8cada"
    background: "#181c20"
    card-background: "#28323b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#7097B6"
    link-hover: "#a0b9ce"

message:
  url: https://learnder.org/
  style: "is-dark"
  title: "👋 早上中午晚上好"
  content: "导航站也是时候更新了，目前更换了技术栈，如果你有什么好的站点，可以通过 <a href='https://evqxwnt7i70.feishu.cn/share/base/form/shrcnDNZ81hdNkCqeV4Pk8VppEg'>表单提交</a>。"

links:
  - name: "文档"
    icon: "fas fa-book"
    url: "https://learnder.org"
    target: "_blank"
  - name: "仓库"
    icon: "fab fa-github"
    url: "https://github.com/Loudomian/learnder-nav"

services:
  - name: "3D 资产"
    icon: "fas fa-cube"
    items:
      - name: "Blender 示例工程"
        logo: "/assets/site/blender.png"
        subtitle: "来自 Blender 官方的示例工程"
        url: "https://www.blender.org/download/demo-files/"
      - name: "SFMLAB"
        logo: "/assets/site/sfmlab.png"
        subtitle: "最大的第三方 SFM 模型库"
        tag: "NSFW"
        tagstyle: "is-warning"
        url: "https://sfmlab.com/"
      - name: "Smutbase"
        logo: "/assets/site/smutbase.png"
        subtitle: "最出名的 3D 同人模型库"
        tag: "NSFW"
        tagstyle: "is-warning"
        url: "https://smutba.se"
      - name: "Open3DLab"
        logo: "/assets/site/open3dlab.png"
        subtitle: "Smutbase 的河蟹版本"
        url: "https://open3dlab.com"
      - name: "DeviantArt"
        logo: "/assets/site/deviantart.png"
        subtitle: "XNALara(XPS) 模型库，最大的艺术家分享网站"
        tag: "NSFW"
        tagstyle: "is-warning"
        url: "https://www.deviantart.com/"
      - name: "模之屋"
        logo: "/assets/site/aplaybox.png"
        subtitle: "二次元模型创作分享社区"
        url: "https://www.aplaybox.com/"
      - name: "Pack 3D models"
        logo: "/assets/site/p3dm.png"
        subtitle: "俄罗斯的 3D 游戏模型库"
        url: "https://p3dm.ru/"
      - name: "Poly Haven"
        logo: "/assets/site/polyhaven.png"
        subtitle: "一个出名的 CC0 资产库，包含 HDRi，材质和模型"
        url: "https://polyhaven.com/"
      - name: "ambientCG"
        logo: "/assets/site/ambientcg.png"
        subtitle: "新兴 CC0 资产库"
        url: "https://ambientcg.com/"
      - name: "Render-State"
        logo: "/assets/site/render-state.png"
        subtitle: "Daz3D 素材究极开心网"
        url: "https://render-state.to/"
      - name: "3DLOAD"
        logo: "/assets/site/3dload.png"
        subtitle: "Daz3D 素材二号开心网"
        url: "https://3d-load.net/"
      - name: "DAZ 3D - Poster"
        logo: "/assets/site/daz3d-poser.png"
        subtitle: "Daz3D 素材三号开心网"
        url: "https://daz3d-poser.net/"
      - name: "Blender布的"
        logo: "/assets/site/blenderco.png"
        subtitle: "一个 Blender 开心资产站"
        url: "https://blenderco.cn/"
      - name: "画忆妙妙屋"
        logo: "/assets/site/iiicg.png"
        subtitle: "精品 3D 开心资产库"
        url: "https://www.iiicg.com/"
  - name: "3D 商城"
    icon: "fas fa-shopping-cart"
    items:
      - name: "Fab"
        logo: "/assets/site/fab.png"
        subtitle: "EpicGames 家的大杂烩，每月还有免费大礼包"
        url: "https://www.fab.com/"
      - name: "RenderHub"
        logo: "/assets/site/renderhub.png"
        subtitle: "一个面向创作者的 3D 素材商店"
        tag: "免费, 付费, NSFW"
        tagstyle: "is-warning"
        url: "https://www.renderhub.com/"
      - name: "Renderosity"
        logo: "/assets/site/renderosity.png"
        subtitle: "一个数字艺术社区，供 CG 艺术家购买和销售 2D 和 3D 资产"
        tag: "免费, 付费, NSFW"
        tagstyle: "is-warning"
        url: "https://www.renderosity.com/"
      - name: "Forender"
        logo: "/assets/site/forender.png"
        subtitle: "Daz3D 同人资产商店"
        tag: "付费, 科学上网, NSFW"
        tagstyle: "is-warning"
        url: "https://www.forender.com/"
      - name: "Renderotica"
        logo: "/assets/site/renderotica.png"
        subtitle: "Daz3D 一体化怪东西社区商店"
        tag: "免费, 付费, NSFW, NSFL"
        tagstyle: "is-danger"
        url: "https://www.renderotica.com/"
      - name: "3D Scan Store"
        logo: "/assets/site/3dscanstore.png"
        subtitle: "性价比最高的扫描模型商城"
        tag: "免费, 付费, NSFW"
        tagstyle: "is-warning"
        url: "https://www.3dscanstore.com/"
      - name: "Triplegangers"
        logo: "/assets/site/triplegangers.png"
        subtitle: "专一的人体扫描模型商城"
        tag: "免费, 付费"
        url: "https://triplegangers.com/"
      - name: "3D.SK"
        logo: "/assets/site/3d.sk.png"
        subtitle: "多样的模型图片/扫描资产商城"
        tag: "免费, 付费, NSFW"
        tagstyle: "is-warning"
        url: "https://www.3d.sk/"
  - name: "3D 个人分享"
    icon: "fas fa-user"
    items:
      - name: "Ram@Crossmind"
        logo: "/assets/site/crossmindstudio.png"
        subtitle: "CrossMind Studio 的高质量工程文件"
        tag: "付费, 科学上网"
        url: "https://crossmindstudio.gumroad.com/"
      - name: "Simon Lee"
        logo: "/assets/site/simonxxoo.png"
        subtitle: "一个热衷在 Blender 实现油画风格的国人大佬分享的资产"
        tag: "付费, 科学上网"
        url: "https://simonxxoo.gumroad.com/"
      - name: "C&C Studio"
        logo: "/assets/site/ccstudio30.png"
        subtitle: "来自多米尼加共和国和意大利的两位 3D 建模师分享的资产"
        tag: "付费, 科学上网"
        url: "https://ccstudio30.gumroad.com/"
      - name: "Ben"
        logo: "/assets/site/bbbn19.png"
        subtitle: "有趣的几何节点，材质等程序化资产"
        tag: "付费, 科学上网"
        url: "https://bbbn19.gumroad.com/"
      - name: "Kristof Dedene"
        logo: "/assets/site/kdedene.png"
        subtitle: "三渲二，类宫崎骏的风格化资产"
        tag: "付费, 科学上网"
        url: "https://kdedene.gumroad.com/"
      - name: "Amin Missaoui"
        logo: "/assets/site/aminmissaoui.png"
        subtitle: "技术创作者，分享的程序化资产"
        tag: "付费, 科学上网"
        url: "https://aminmissaoui.gumroad.com/"
  - name: "音频"
    icon: "fas fa-volume-up"
    items:
      - name: "Adobe Audition Sound Effects"
        logo: "/assets/site/adobe.png"
        subtitle: "Adobe 创意云提供的免版税音效合集"
        url: "https://www.adobe.com/products/audition/offers/AdobeAuditionDLCSFX.html"
      - name: "小森平的免费音效库"
        logo: "/assets/site/taira-komori.png"
        subtitle: "日本音乐人的免费音效库"
        url: "https://taira-komori.jpn.org/freesoundtw.html"
      - name: "魔王魂"
        logo: "/assets/site/maou.png"
        subtitle: "CC BY 4.0 可商用音乐库"
        url: "https://maou.audio/"
      - name: "FreePD"
        logo: "/assets/site/freepd.png"
        subtitle: "免费公众领域曲库"
        url: "https://freepd.com/"
      - name: "OtoLogic"
        logo: "/assets/site/otologic.png"
        subtitle: "由专业的声音创作者制作的 CC BY 4.0 音频库"
        url: "https://otologic.jp/"
      - name: "Musopen"
        logo: "/assets/site/musopen.png"
        subtitle: "免费向公众提供不受版权限制的录音，乐谱和教学"
        url: "https://musopen.org/zh-hans/music/"
      - name: "Looperman"
        logo: "/assets/site/looperman.png"
        subtitle: "循环音频社区，由社区成员一同创作免费可商用的循环音频片段"
        url: "https://www.looperman.com/"
      - name: "耳聆网"
        logo: "/assets/site/ear0.png"
        subtitle: "中国最专业的声音分享平台，用户共享高质量音频素材"
        url: "https://www.ear0.com/"
  - name: "算力平台"
    icon: "fas fa-server"
    items:
      - name: "飞桨 AI Studio"
        logo: "/assets/site/aistudio.png"
        subtitle: "百度的人工智能训练平台，白嫖"
        url: "https://aistudio.baidu.com/"
      - name: "AutoDL"
        logo: "/assets/site/autodl.png"
        subtitle: "品质 GPU 租用平台，高性价比"
        url: "https://www.autodl.com/"
      - name: "Gpushare Cloud"
        logo: "/assets/site/gpushare.png"
        subtitle: "专注 AI 行业的共享算力平台，高性价比"
        url: "https://gpushare.com/auth/register?user=18*****4742&fromId=4f880081aa18&source=link"
      - name: "OpenBayes"
        logo: "/assets/site/openbayes.png"
        subtitle: "简单、快速构建高性能 AI 服务，可白嫖，高性价比"
        url: "https://openbayes.com/console/signup?r=Loudomian_j17I"
  - name: "文档素材"
    icon: "fas fa-file-powerpoint"
    items:
      - name: "OfficePLUS"
        logo: "/assets/site/officeplus.png"
        subtitle: "微软官方 PPT 模板"
        url: "https://www.officeplus.cn/"
      - name: "优品PPT"
        logo: "/assets/site/ypppt.png"
        subtitle: "一个有情怀的免费 PPT 模板下载站"
        url: "https://www.ypppt.com/"
      - name: "HiPPTer"
        logo: "/assets/site/hippter.png"
        subtitle: "精品 PPT 模板免费下载"
        url: "http://www.hippter.com/"
  - name: "在线工具"
    icon: "fas fa-toolbox"
    items:
      - name: "ITDOG"
        logo: "/assets/site/itdog.png"
        subtitle: "好用的在线 Ping，MTR，DNS 查询工具"
        url: "https://www.itdog.cn/"
      - name: "GTmetrix"
        logo: "/assets/site/gtmetrix.png"
        subtitle: "在线监测网站访问速度和性能"
        url: "https://gtmetrix.com/"
      - name: "Ping.Sx"
        logo: "/assets/site/misaka.png"
        subtitle: "在线全球 Ping 指定 IP 或 域名，查询丢包延迟"
        url: "https://ping.sx/ping"
      - name: "Can I use"
        logo: "/assets/site/caniuse.png"
        subtitle: "检查浏览器可使用的 CSS 和 JavaScript 功能"
        url: "https://caniuse.com/"
      - name: "The Favicon Finder"
        logo: "/assets/site/besticon.png"
        subtitle: "网站图标下载工具"
        url: "https://besticon.herokuapp.com/"
      - name: "removebg"
        logo: "/assets/site/removebg.png"
        subtitle: "超级好用的背景消除工具，有免费额度"
        url: "https://www.remove.bg/r/xmmEBqfKMa954GowMxcDv5Ah?locale=zh"
      - name: "Convertio"
        logo: "/assets/site/convertio.png"
        subtitle: "在线万能格式转换工具"
        url: "https://convertio.co/zh/"
      - name: "TinyPNG"
        logo: "/assets/site/tinypng.png"
        subtitle: "高质量高效率的图片压缩工具"
        url: "https://tinypng.com/"
      - name: "ASCII Art Generator"
        logo: "/assets/site/3dload.png"
        subtitle: "ACSII 艺术字体生成工具"
        url: "http://patorjk.com/software/taag"
  - name: "分享储存"
    icon: "fas fa-cloud-upload-alt"
    items:
      - name: "文叔叔"
        logo: "/assets/site/wenshushu.png"
        subtitle: "无需登录的国内在线传"
        url: "https://www.wenshushu.cn/"
      - name: "SwissTransfer"
        logo: "/assets/site/swisstransfer.png"
        subtitle: "大容量，长时间存储的临时分享"
        url: "https://www.swisstransfer.com/"
      - name: "WeTransfer"
        logo: "/assets/site/wetransfer.png"
        subtitle: "奶牛快传的爹，且更好用"
        url: "https://wetransfer.com/"
      - name: "Ufile"
        logo: "/assets/site/ufile.png"
        subtitle: "分享文件，但有一定限制"
        url: "https://ufile.io/"
      - name: "钛盘"
        logo: "/assets/site/tmp-link.png"
        subtitle: "好用的文件中转站，现在限制较多"
        url: "https://tmp.link/"
  - name: "插画图标"
    icon: "fas fa-paint-brush"
    items:
      - name: "unDraw"
        logo: "/assets/site/undraw.png"
        subtitle: "免费，矢量插画，可在线调节颜色"
        url: "https://undraw.co/illustrations"
      - name: "Blush"
        logo: "/assets/site/blush.png"
        subtitle: "色彩鲜明的插画，还可以在figma和sketch中安装插件"
        url: "https://blush.design/zh-CN"
      - name: "Free Illustrations"
        logo: "/assets/site/sketchvalley.png"
        subtitle: "一个免费的高质量矢量插画资源"
        url: "https://sketchvalley.com/"
      - name: "RESHOT"
        logo: "/assets/site/reshot.png"
        subtitle: "免费图标、插图，可商用"
        url: "https://www.reshot.com/"
      - name: "IconPark"
        logo: "/assets/site/iconpark.png"
        subtitle: "免费，规范、统一、多风格切换（字节跳动）"
        url: "https://iconpark.oceanengine.com/home"
      - name: "Iconfont"
        logo: "/assets/site/iconfont.png"
        subtitle: "免费，图标数量丰富，有插画，需登录（阿里）"
        url: "https://www.iconfont.cn"
      - name: "Remix Icon"
        logo: "/assets/site/remixicon.png"
        subtitle: "免费，精致统一的开源图标"
        url: "https://remixicon.com"
  - name: "色彩"
    icon: "fas fa-palette"
    items:
      - name: "ColorDrop"
        logo: "/assets/site/colordrop.png"
        subtitle: "四色色卡"
        url: "https://colordrop.io"
      - name: "中国色"
        logo: "/assets/site/zhonguose.png"
        subtitle: "中国传统色"
        url: "http://zhongguose.com"
      - name: "Nippon Colors"
        logo: "/assets/site/nipponcolors.png"
        subtitle: "日本传统色"
        url: "https://nipponcolors.com"
      - name: "WebGradients"
        logo: "/assets/site/webgradients.png"
        subtitle: "优美的渐变色"
        url: "https://webgradients.com"
      - name: "BrandColors"
        logo: "/assets/site/brandcolors.png"
        subtitle: "各大公司品牌色"
        url: "https://brandcolors.net/"
      - name: "Mesh Gradients"
        logo: "/assets/site/mesh-gradients.png"
        subtitle: "不规则渐变"
        url: "https://products.ls.graphics/mesh-gradients/"
      - name: "Open Color"
        logo: "/assets/site/opencolor.png"
        subtitle: "13个色系，每种色系分10个明度"
        url: "https://yeun.github.io/open-color/"
      - name: "ColorBox"
        logo: "/assets/site/colorbox.png"
        subtitle: "自动生成色彩梯度"
        url: "https://colorbox.io/"
  - name: "图片"
    icon: "fas fa-image"
    items:
      - name: "Unsplash"
        logo: "/assets/site/unsplash.png"
        subtitle: "免费，由世界各地创作者提供的高质量图片"
        url: "https://unsplash.com"
      - name: "Pexels"
        logo: "/assets/site/pexels.png"
        subtitle: "免费，包括图片和视频"
        url: "https://www.pexels.com"
      - name: "Pixabay"
        logo: "/assets/site/pixabay.png"
        subtitle: "免费，超过 250 万张高质量的作品，包括图片、视频和音乐"
        url: "https://pixabay.com"
      - name: "SplitShire"
        logo: "/assets/site/splitshire.png"
        subtitle: "免费，精美独特的图片库"
        url: "https://www.splitshire.com"
      - name: "StolSnap"
        logo: "/assets/site/stocksnap.png"
        subtitle: "免费，每天都更新图片"
        url: "https://stocksnap.io"
      - name: "IMGBIN"
        logo: "/assets/site/imgbin.png"
        subtitle: "免费，由设计师创建的数百万个透明 PNG 文件"
        url: "https://imgbin.com"
      - name: "POND5"
        logo: "/assets/site/pond5.png"
        subtitle: "公共领域，有图片，音乐，模型等数千个历史媒体文件"
        url: "https://www.pond5.com/public-domain"
      - name: "Streetwill"
        logo: "/assets/site/streetwill.png"
        subtitle: "免费高质量街拍图片"
        url: "http://streetwill.co"
  - name: "视频"
    icon: "fas fa-video"
    items:
      - name: "ProductionCrate"
        logo: "/assets/site/productioncrate.png"
        subtitle: "后期合成视频/音频/3D素材，商用首选"
        tag: "免费, 付费"
        url: "https://productioncrate.com/"
      - name: "Coverr"
        logo: "/assets/site/coverr.png"
        subtitle: "提供了超多高质量航拍视频的网站，不用注册，可直接下载商用"
        url: "https://coverr.co"
      - name: "Mazwai"
        logo: "/assets/site/mazwai.png"
        subtitle: "这个网站每个视频都是经过手工精选的，画面和角度都很刁钻"
        url: "https://mazwai.com"
      - name: "Videvo"
        logo: "/assets/site/videvo.png"
        subtitle: "一个致力打造全球第一的视频素材网站，提供数量丰富素材，免版权"
        url: "https://www.videvo.net"
  - name: "逆向工程"
    icon: "fas fa-code"
    items:
      - name: "编动小组"
        logo: "/assets/site/bdgroup-lab.png"
        subtitle: "Autodesk 逆向工具"
        url: "https://www.bdgroup-lab.com/"
      - name: "vposy"
        logo: "/assets/site/vposy.png"
        subtitle: "Adobe 全家福（需关注账号查看置顶文章）"
        url: "https://weibo.com/vposy"
      - name: "Repacks"
        logo: "/assets/site/lrepacks.png"
        subtitle: "著名的俄罗斯逆向软件网站"
        url: "https://lrepacks.net/"
      - name: "Modme Wiki"
        logo: "/assets/site/modme.png"
        subtitle: "COD系列，Apex 和 Doom 的逆向工具"
        url: "https://wiki.modme.co/"
      - name: "Gildor"
        logo: "/assets/site/gildor.png"
        subtitle: "Unreal Engine 逆向工具和论坛"
        url: "https://www.gildor.org/"
      - name: "XeNTax"
        logo: "/assets/site/xentax.png"
        subtitle: "游戏逆向论坛"
        url: "https://forum.xentax.com/"
      - name: "ResidentEvil Modding"
        logo: "/assets/site/residentevilmodding.png"
        subtitle: "Resident Evil 系列逆向论坛"
        url: "https://residentevilmodding.boards.net/thread/10567/pak-tex-editing-tool"
  - name: "教程文档"
    icon: "fas fa-book"
    items:
      - name: "Pte Jack 的指南"
        logo: "/assets/site/steam.png"
        subtitle: "Source Filmmaker 指南合集"
        tag: "科学上网"
        url: "https://steamcommunity.com/id/PteJack/myworkshopfiles/?section=guides"
      - name: "Source2 Filmmaker 开发者指南"
        logo: "/assets/site/steam.png"
        subtitle: "Half-Life: Alyx 的 SDK 文档"
        url: "https://developer.valvesoftware.com/wiki/Half-Life:_Alyx_Workshop_Tools:zh-cn"
      - name: "中文文案排版指北"
        logo: "/assets/site/mazhuang.png"
        subtitle: "统一中文文案、排版的相关用法"
        url: "https://mazhuang.org/wiki/chinese-copywriting-guidelines/"
      - name: "Jan van den Hemel"
        logo: "/assets/site/janvandenhemel.png"
        subtitle: "Jan van den Hemel 的优质 Blender 短篇教程"
        tag: "科学上网"
        url: "https://twitter.com/JanvandenHemel"
      - name: "Emoji XD"
        logo: "/assets/site/emojixd.png"
        subtitle: "线上Emoji百科全书，支持关键词搜索"
        url: "https://emojixd.com"
      - name: "Git Emoji 使用指南"
        logo: "/assets/site/git-emoji-cn.png"
        subtitle: "Emoji 在 Git 提交时的使用指南"
        url: "http://wejectchan.gitee.io/git-emoji-user-guide/"